### ISSUE TITLE
Lights

### ISSUE THREAD

**Issue by damirken** [robi29/GTA-IV-Shaders#7]
Light Street lights only appear when they are too close, just like headlights, if use without fusion fix

**Comment by MagicAl6244225** [comment]
> Light Street lights only appear when they are too close, just like headlights, if use without fusion fix

As the changelog says, from v.1.0.3 the shaders aren't meant to be used without FusionFix.

**Comment by robi29** [comment]
Yes, FusionFix is required, because one vertex shader doesn't have necessary constants needed for z-fighting fix: https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/blob/master/source/dllmain.cpp#L1717
